"""empty message

Revision ID: 085bd6206df2
Revises: bc77b5447ecf
Create Date: 2025-03-01 14:42:49.371145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085bd6206df2'
down_revision = 'bc77b5447ecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
